### ISSUE TITLE
allowedDependencies

### ISSUE THREAD

**Issue by u650080** [namics/gradle-license-enforce-plugin#1]
Hi ,
is it possible to use regular expression to avoid write all  allowedDependencies one by one?

**Comment by andreschaefer** [comment]
Hello.
With Version  1.2.1 an option was introduced to define Dependencies without Version. This way it does not need to be updated with dependency updates.
The definition of allowed Dependencies is done that strict to enforce developers to check questionable dependencies carefully. Using (to) generic Regexes would make this plugin useless.
