### ISSUE TITLE
Is there a way to add strings to the license dictionary?

### ISSUE THREAD

**Issue by ketan** [namics/gradle-license-enforce-plugin#3]
I'd like to be able to quickly add to the existing dictionary additional aliases that I'm seeing specific to my project.

Is there a way I can do this?

**Comment by andreschaefer** [comment]
Hello @ketan 

You may 
- add a `license-dictionary.yaml` to your `project.projectDir`
- place a `yaml`somewhere else and add it to the Task-Configuration

```
tasks.enforceLicenses {
    dictionaries = listOf("my-specific.yml")
}
```

If there are common well known aliases you may also create a pull request here to evolve an up to date list.

**Comment by andreschaefer** [comment]
added more config info to README.md

**Comment by ketan** [comment]
Thank you very much!
